Repository MBTI-Channel/server, pull requests merged in 2022-08, with the labels that each got.

#100 Docs: typeorm.md 정의 및 특징 업데이트
  docs/typeorm.md
Labels: docs

#104 Test: 대댓글 작성 service 테스트코드 추가
  test/unit/modules/comment/comment.service.test.ts
Labels: test

#106 Docs: inversify.md scope 옵션별 차이 추가
  docs/inversify.md
Labels: docs

#110 Docs: update class-validator.md
  docs/class-validator.md
Labels: docs

#112 Feat: 내 작성글 조회 API
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/user/dto/get-my-posts.dto.ts
  src/modules/user/dto/index.ts
  src/modules/user/interfaces/IUser.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
  src/swagger/openapi.yaml
  src/swagger/paths/users/posts.yaml
  src/swagger/responses/users/id.posts.get.yaml
  src/swagger/responses/users/posts.get.yaml
Labels: feat

#114 Add: 개발 환경 docker compose
  README.md
  docker-compose.dev.yml
  docs/dev-with-docker.md
  src/core/database/redis.service.ts
  src/datasource.ts
Labels: chore

#121 Feat: 신고 API
  src/core/container.core.ts
  src/core/types.core.ts
  src/modules/comment/comment.service.ts
  src/modules/comment/interfaces/IComment.service.ts
  src/modules/index.controller.ts
  src/modules/post/interfaces/IPost.service.ts
  src/modules/post/post.service.ts
  src/modules/report/dto/index.ts
  src/modules/report/dto/report.dto.ts
  src/modules/report/entity/report.entity.ts
  src/modules/report/helper/report-target-type-transforemr.ts
  src/modules/report/interfaces/IReport.repository.ts
  src/modules/report/interfaces/IReport.service.ts
  src/modules/report/report.controller.ts
  src/modules/report/report.module.ts
  src/modules/report/report.repository.ts
  src/modules/report/report.service.ts
  src/shared/api/discord-api.service.ts
  src/shared/api/interfaces/IApi-webhook.service.ts
  src/shared/enum.shared.ts
Labels: feat

#122 Feat: trend 생성
  src/core/container.core.ts
  src/core/types.core.ts
  src/modules/like/dto/like-response.dto.ts
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
  src/modules/trend/entity/trend.entity.ts
  src/modules/trend/interfaces/ITrend.service.ts
  src/modules/trend/interfaces/ITrendRepository.ts
  src/modules/trend/trend.module.ts
  src/modules/trend/trend.repository.ts
  src/modules/trend/trend.service.ts
  src/shared/constant.shared.ts
Labels: feat

#123 Feat: 신고 디스코드 알림
  src/config/index.ts
  src/shared/api/discord-api.service.ts
Labels: feat

#125 Feat: comment is valid 메서드
  src/modules/comment/comment.service.ts
  src/modules/report/report.service.ts
Labels: feat

#126 Feat: 게시글 신고수 증가
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
Labels: feat

#127 Docs: swagger 신고 API 추가
  src/swagger/openapi.yaml
  src/swagger/paths/reports/index.yaml
  src/swagger/responses/reports/index.post.yaml
Labels: docs

#133 Feat: 닉네임 업데이트 API
  src/modules/user/dto/index.ts
  src/modules/user/dto/update-user-nickname.dto.ts
  src/modules/user/interfaces/IUser.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: feat

#128 Docs: docs 업데이트
  docs/README.md
  docs/dev-with-docker.md
Labels: docs

#136 Update: page info dto 변수명에 맞게 수정
  src/modules/comment/comment.service.ts
  src/modules/post/post.service.ts
  src/shared/page/dto/page-info.dto.ts
Labels: update

#134 Feat: survey create API
  src/core/container.core.ts
  src/core/types.core.ts
  src/modules/index.controller.ts
  src/modules/post/dto/index.ts
  src/modules/post/post.controller.ts
  src/modules/survey/dto/create-survey.dto.ts
  src/modules/survey/dto/index.ts
  src/modules/survey/dto/survey-response.dto.ts
  src/modules/survey/entity/survey.entity.ts
  src/modules/survey/interfaces/ISurvey.repository.ts
  src/modules/survey/interfaces/ISurvey.service.ts
  src/modules/survey/survey.controller.ts
  src/modules/survey/survey.module.ts
  src/modules/survey/survey.repository.ts
  src/modules/survey/survey.service.ts
Labels: feat

#137 Fix: swagger 댓글 API 전체적으로 수정
  src/swagger/openapi.yaml
  src/swagger/paths/comments/id.yaml
  src/swagger/paths/comments/index.yaml
  src/swagger/paths/comments/replies.yaml
  src/swagger/responses/comments/index.get.yaml
  src/swagger/responses/comments/index.post.yaml
  src/swagger/responses/comments/replies.get.yaml
  src/swagger/responses/comments/replies.post.yaml
Labels: docs

#140 Update: posts pagination
  src/modules/comment/comment.service.ts
  src/modules/notifications/notification.service.ts
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
  src/shared/page/dto/page-infinite-scroll-info.dto.ts
Labels: update

#141 Fix: 회원가입 API 쿠키에 Refresh 설정 추가
  src/modules/user/user.controller.ts
Labels: fix, update

#142 Feat: 로그아웃 API
  src/modules/user/interfaces/IUser.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: feat

#143 Update: post pagination nextId
  src/modules/post/dto/get-all-post.dto.ts
  src/modules/post/dto/get-trend.dto.ts
  src/modules/post/dto/search-post.dto.ts
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
Labels: update

#144 Docs: 회원 탈퇴 API swagger 추가
  src/swagger/paths/users/id.yaml
  src/swagger/paths/users/me.yaml
  src/swagger/responses/users/id.delete.yaml
  src/swagger/responses/users/me.delete.yaml
Labels: docs

#145 Docs: swagger 로그아웃 api 개선
  src/swagger/paths/users/logout.yaml
  src/swagger/responses/users/logout.delete.yaml
Labels: docs

#146 Update: post pagination where 동적으로 처리
  src/modules/post/post.repository.ts
Labels: update

#147 Chore: migration 설정
  package.json
  src/datasource.ts
Labels: chore

#148 Chore: 기본 카테고리 마이그레이션 추가
  src/migrations/1660457303391-create-base-category.ts
Labels: chore

#149 Fix: create-base-category 마이그레이션 동기화 문제
  src/migrations/1660457303391-create-base-category.ts
Labels: fix

#152 Docs: Swagger 유저 개선
  src/swagger/openapi.yaml
  src/swagger/paths/users/comments.yaml
  src/swagger/paths/users/id.yaml
  src/swagger/paths/users/index.yaml
  src/swagger/paths/users/login.yaml
  src/swagger/paths/users/posts.yaml
  src/swagger/responses/users/access-token.get.yaml
  src/swagger/responses/users/comments.get.yaml
  src/swagger/responses/users/id.get.yaml
  src/swagger/responses/users/id.patch.yaml
  src/swagger/responses/users/index.post.yaml
  src/swagger/responses/users/login.post.yaml
  src/swagger/responses/users/me.get.yaml
Labels: docs

#154 Docs: update swagger post
  src/swagger/openapi.yaml
  src/swagger/paths/posts/id.yaml
  src/swagger/paths/posts/index.yaml
  src/swagger/paths/posts/trending.yaml
  src/swagger/responses/posts/id.delete.yaml
  src/swagger/responses/posts/id.get.yaml
  src/swagger/responses/posts/id.patch.yaml
  src/swagger/responses/posts/index.get.yaml
  src/swagger/responses/posts/index.post.yaml
  src/swagger/responses/posts/trending.get.yaml
Labels: docs

#151 Update: category search
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
Labels: update

#157 Refactor: post create dto
  src/modules/post/dto/create-post.dto.ts
  src/modules/post/interfaces/IPost.service.ts
  src/modules/post/post.controller.ts
  src/modules/post/post.service.ts
  src/swagger/paths/posts/index.yaml
Labels: update

#158 Update: post search
  src/modules/category/entity/category.entity.ts
  src/modules/post/dto/search-post.dto.ts
  src/modules/post/interfaces/IPost.repository.ts
  src/modules/post/post.repository.ts
  src/modules/post/post.service.ts
  src/shared/enum.shared.ts
Labels: update

#156 Feat: 유저 MBTI 업데이트 API
  src/core/container.core.ts
  src/core/types.core.ts
  src/migrations/1660664316256-create-upate-log-table.ts
  src/modules/update-log/entity/update-log.entity.ts
  src/modules/update-log/interfaces/IUpdate-log.repository.ts
  src/modules/update-log/interfaces/IUpdate-log.service.ts
  src/modules/update-log/update-log.module.ts
  src/modules/update-log/update-log.repository.ts
  src/modules/update-log/update-log.service.ts
  src/modules/user/dto/index.ts
  src/modules/user/dto/udpate-user-mbti.dto.ts
  src/modules/user/entity/user.entity.ts
  src/modules/user/interfaces/IUser.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
  src/shared/enum.shared.ts
  src/shared/type.shared.ts
Labels: chore, feat

#159 Docs: swagger post search
  src/swagger/paths/posts/search.yaml
Labels: docs

#161 Docs: swagger 닉네임 업데이트 API
  src/swagger/openapi.yaml
  src/swagger/paths/users/id.bookmarks.yaml
  src/swagger/paths/users/id.survey.yaml
  src/swagger/paths/users/me.nickname.yaml
  src/swagger/responses/users/id.bookmarks.get.yaml
  src/swagger/responses/users/id.survey.get.yaml
  src/swagger/responses/users/me.nickname.patch.yaml
Labels: docs

#160 Feat: 북마크한 글 조회 API
  src/modules/bookmark/bookmark.repository.ts
  src/modules/bookmark/bookmark.service.ts
  src/modules/bookmark/dto/bookmark-post-response.dto.ts
  src/modules/bookmark/interfaces/IBookmark.repository.ts
  src/modules/bookmark/interfaces/IBookmark.service.ts
  src/modules/update-log/update-log.service.ts
  src/modules/user/user.controller.ts
Labels: feat

#162 Update: post response
  src/modules/post/dto/post-response.dto.ts
  src/swagger/responses/posts/id.get.yaml
  src/swagger/responses/posts/id.patch.yaml
  src/swagger/responses/posts/index.get.yaml
  src/swagger/responses/posts/index.post.yaml
  src/swagger/responses/posts/search.get.yaml
  src/swagger/responses/posts/trending.get.yaml
Labels: update

#165 Fix: 구현체 주입 수정
  src/modules/auth/auth.service.ts
  src/modules/login-log/login-log.service.ts
Labels: fix

#164 Docs: swagger 북마크한글 조회 API 추가
  src/swagger/openapi.yaml
  src/swagger/paths/users/bookmarks.yaml
  src/swagger/responses/users/bookmarks.get.yaml
  src/swagger/responses/users/posts.get.yaml
Labels: docs

#163 Docs: swagger 유저 MBTI 업데이트 API 추가
  src/swagger/openapi.yaml
  src/swagger/paths/users/me.mbti.yaml
  src/swagger/responses/users/me.mbti.patch.yaml
Labels: docs

#167 !HOTFIX: 대댓글 조회 버그
  src/modules/comment/comment.service.ts
  src/swagger/responses/comments/replies.get.yaml
Labels: docs, fix, update

#168 Fix: 댓글 조회시 totalCount 값 불일치 수정
  src/modules/comment/comment.repository.ts
  src/modules/comment/comment.service.ts
  src/modules/comment/interfaces/IComment.repository.ts
Labels: fix

#169 !HOTFIX: 게시글 조회 버그
  src/modules/post/post.service.ts
  src/swagger/responses/posts/index.get.yaml
  src/swagger/responses/posts/search.get.yaml
  src/swagger/responses/posts/trending.get.yaml
Labels: bug, fix

#170 Chore: package.json 마이그레이션 script 로컬에서 적용되게 수정
  package.json
Labels: chore

#172 Chore: CODEOWNERS 추가
  .github/CODEOWNERS 
Labels: chore

#173 Feat: 게시글 생성시 파일 업로드
  src/core/container.core.ts
  src/core/types.core.ts
  src/migrations/1660907288956-migrations.ts
  src/modules/file/entity/file.entity.ts
  src/modules/file/file.module.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.service.ts
  src/modules/file/helper/file-target-type-transormer.ts
  src/modules/file/interfaces/IFile.repository.ts
  src/modules/file/interfaces/IFile.service.ts
  src/modules/post/dto/create-post.dto.ts
  src/modules/post/dto/post-response.dto.ts
  src/modules/post/entity/post.entity.ts
  src/modules/post/interfaces/IPost.service.ts
  src/modules/post/post.controller.ts
  src/modules/post/post.service.ts
  src/shared/enum.shared.ts
Labels: feat, update

#175 Update: swagger post create
  src/modules/post/dto/create-post.dto.ts
  src/modules/post/interfaces/IPost.service.ts
  src/modules/post/post.controller.ts
  src/modules/post/post.service.ts
  src/swagger/paths/posts/index.yaml
Labels: docs, update

#176 Add: file delete
  src/modules/file/file.repository.ts
  src/modules/file/file.service.ts
  src/modules/file/interfaces/IFile.repository.ts
  src/modules/file/interfaces/IFile.service.ts
  src/modules/post/post.controller.ts
  src/modules/post/post.service.ts
Labels: feat

#177 Update: notification service 조회 next id 로직
  src/modules/notifications/interfaces/INotification.service.ts
  src/modules/notifications/notification.controller.ts
  src/modules/notifications/notification.repository.ts
  src/modules/notifications/notification.service.ts
Labels: update

#180 Fix: user 알림 조회 API
  src/modules/notifications/dto/index.ts
  src/modules/notifications/dto/notification-page-response.dto.ts
  src/modules/notifications/interfaces/INotification.repository.ts
  src/modules/notifications/notification.repository.ts
  src/modules/notifications/notification.service.ts
  src/swagger/responses/notifications/index.get.yaml
Labels: docs, fix, update

#183 Fix: CheckLoginStatus 미들웨어 요청 인증 헤더에서 null일 경우 추가
  src/middlewares/check-login-status.middleware.ts
Labels: fix

#179 Feat: file update
  src/modules/file/file.repository.ts
  src/modules/file/file.service.ts
  src/modules/file/interfaces/IFile.repository.ts
  src/modules/file/interfaces/IFile.service.ts
  src/modules/post/dto/create-post.dto.ts
  src/modules/post/dto/update-post.dto.ts
  src/modules/post/interfaces/IPost.service.ts
  src/modules/post/post.controller.ts
  src/modules/post/post.service.ts
  src/swagger/paths/posts/id.yaml
  src/swagger/paths/posts/index.yaml
Labels: update

#184 Update: user repo update 수정후 user service에 적용
  src/modules/user/interfaces/IUser.repository.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
Labels: update
